name: 'W-18'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '05 04 */2 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  H:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v3
          
        - name: Setup FFmpeg using versions
          uses: Iamshankhadeep/setup-ffmpeg@v1.2
          with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
           token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Setup Environment
          run: |
           pip install --upgrade pip
           pip install Pillow pyscreenshot
           pip install -r ./requirements.txt
           
        - name: 'Renew-H'
          env:
            URL_BASE: ${{ secrets.URL_BASE_H }}
            USER_ID: ${{ secrets.USER_ID_18 }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}

          run: |
            xvfb-run python3 ./main.py
